[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$JuT8/x8DYCwFgNAaw7hXig$3.B.n5LfZUYlaT4uqzzYzApAXXZ3LbLcvZhHy6ph8S/am6ypjeaqlKtU1PUsxqBE6zeqk9U/NJOE7cHh9zcDvA

